/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./*.html', './docs/**/*.html'],
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#e1e0ff',
        'surface-container': '#171f33',
        'on-secondary': '#003825',
        'on-primary-container': '#0d0096',
        outline: '#a8a7b8',
        'on-tertiary-fixed-variant': '#703700',
        'surface-container-low': '#131b2e',
        'on-error-container': '#ffdad6',
        'surface-container-highest': '#2d3449',
        'secondary-fixed-dim': '#45dfa4',
        'surface-variant': '#2d3449',
        'primary-fixed-dim': '#c0c1ff',
        background: '#0b1326',
        'on-secondary-container': '#00452e',
        'secondary-fixed': '#68fcbf',
        'surface-container-lowest': '#060e20',
        'tertiary-fixed': '#ffdcc5',
        'secondary-container': '#00bd85',
        'on-tertiary': '#4f2500',
        'outline-variant': '#464554',
        error: '#ffb4ab',
        'surface-container-high': '#222a3d',
        'on-primary': '#1000a9',
        'on-surface-variant': '#c7c4d7',
        'inverse-primary': '#494bd6',
        'on-secondary-fixed-variant': '#005137',
        'on-primary-fixed-variant': '#2f2ebe',
        'on-tertiary-fixed': '#301400',
        'inverse-on-surface': '#283044',
        'primary-container': '#8083ff',
        tertiary: '#ffb783',
        'error-container': '#93000a',
        'on-tertiary-container': '#452000',
        'on-secondary-fixed': '#002114',
        'on-primary-fixed': '#07006c',
        'tertiary-fixed-dim': '#ffb783',
        'surface-bright': '#31394d',
        'surface-tint': '#c0c1ff',
        'on-error': '#690005',
        primary: '#c0c1ff',
        secondary: '#45dfa4',
        surface: '#0b1326',
        'on-background': '#dae2fd',
        'on-surface': '#dae2fd',
        'tertiary-container': '#d97721',
        'surface-dim': '#0b1326',
        'inverse-surface': '#dae2fd',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
